# These are supported funding model platforms

github: [Kingsrook]
# Patreon is also supported, but requires a custom URL
# patreon: Kingsrook
# Open Collective is also supported, but requires a custom URL
# open_collective: Kingsrook
# Ko-fi is also supported, but requires a custom URL
# ko_fi: Kingsrook
# Tidelift is also supported, but requires a custom URL
# tidelift: Kingsrook
# Community Bridge is also supported, but requires a custom URL
# community_bridge: Kingsrook
# Liberapay is also supported, but requires a custom URL
# liberapay: Kingsrook
# IssueHunt is also supported, but requires a custom URL
# issuehunt: Kingsrook
# Otechie is also supported, but requires a custom URL
# otechie: Kingsrook
# Custom URLs are also supported, but require a custom URL
# custom: https://kingsrook.com/support

# Note: This repository is a frontend component of the QQQ framework.
# For main project funding and support, visit: https://github.com/Kingsrook/qqq
