version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - run:
          name: write npmrc
          command: |
            echo "@kingsrook:registry=https://npm.pkg.github.com/" >> .npmrc
            echo "NPM_TOKEN=${NPM_TOKEN}"" >> .npmrc
            echo "@OWNER:registry=https://npm.pkg.github.com/" >> .npmrc
            echo "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" >> .npmrc
            cat .npmrc
      - node/install:
          node-version: '16.13'
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Start web server
          command: npm run start
      - run:
          name: Run cypress tests
          command: |
            curl --retry-delay 5 --retry 10 --retry-connrefused https://localhost:3000
            npm run cypress:run

workflows:
  test:
    jobs:
      - test
