version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install:
          node-version: '16.13'
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Start web server
          command: npm run start
      - run:
          name: Run cypress tests
          command: |
            curl --retry-delay 5 --retry 10 --retry-connrefused https://localhost:3000
            npm run cypress:run

workflows:
  test:
    jobs:
      - test
