version: 2.1

orbs:
  cypress: cypress-io/cypress@2

commands:
  setup:
    steps:
      - checkout
      - run:
          name: write npmrc
          command: |
            echo "@kingsrook:registry=https://npm.pkg.github.com/" >> .npmrc
            echo "NPM_TOKEN=${NPM_TOKEN}" >> .npmrc
            echo "@OWNER:registry=https://npm.pkg.github.com/" >> .npmrc
            echo "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" >> .npmrc

jobs:
  setup-job:
    executor: cypress/base-10
    steps:
      - setup

workflows:
  build:
    jobs:
      - setup-job:
         context: [ qqq-maven-registry-credentials ]
      - cypress/install:
          build: 'npm run build' # run a custom app build step
      - cypress/run:
          requires:
            - cypress/install
          record: true # record results on Cypress Dashboard
          ## parallel: true # split all specs across machines
          ## parallelism: 4 # use 4 CircleCI machines to finish quickly
          ## group: 'all tests' # name this group "all tests" on the dashboard
          start: 'npm run start' # start server before running tests

