name: 'CI/CD Pipeline'

on:
  push:
    branches: [ main, develop, 'release/*', 'hotfix/*', 'feature/*' ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  publish:
    name: '🚀 Build, Test, and Publish Release (main, rc, hotfix, or snapshot)'
    if: |
      github.ref_name == 'main' ||
      github.ref_name == 'develop' ||
      startsWith(github.ref_name, 'release/') ||
      startsWith(github.ref_name, 'hotfix/')
    uses: Kingsrook/github-actions-library/.github/workflows/reusable-gitflow-publish.yml@release/0.1.0
    with:
      project-type: 'maven'
      java-version: '17'
      maven-args: '-B -q'
      maven-working-directory: '.'
    secrets:
      GPG_PRIVATE_KEY_B64: ${{ secrets.GPG_PRIVATE_KEY_B64 }}
      GPG_KEYNAME: ${{ secrets.GPG_KEYNAME }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
      CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  test:
    name: '🧪 Build and Test Only'
    if: |
      !(
        github.ref_name == 'main' ||
        github.ref_name == 'develop' ||
        startsWith(github.ref_name, 'release/') ||
        startsWith(github.ref_name, 'hotfix/')
      )
    uses: Kingsrook/github-actions-library/.github/workflows/reusable-gitflow-test.yml@release/0.1.0
    with:
      project-type: 'maven'
      java-version: '17'
      maven-args: '-B -q'
      maven-working-directory: '.'
